# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_bulk_update import WorkspaceBulkUpdate

class TestWorkspaceBulkUpdate(unittest.TestCase):
    """WorkspaceBulkUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceBulkUpdate:
        """Test WorkspaceBulkUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceBulkUpdate`
        """
        model = WorkspaceBulkUpdate()
        if include_optional:
            return WorkspaceBulkUpdate(
                id = '',
                resource = openapi_client.models.workspace.Workspace(
                    alias = '', 
                    archived = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    default_permission = 'comment', 
                    description = openapi_client.models.rich_text.RichText(
                        blocks = [
                            null
                            ], ), 
                    id = '', 
                    item_color = 'amber', 
                    item_type = 'bug', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    legacy_id = '', 
                    metadata = openapi_client.models.workspace_workspace_metadata.WorkspaceWorkspaceMetadata(
                        duplicated = True, 
                        template_id = '', 
                        template_workspace_ref = '', 
                        version = '', ), 
                    name = '', 
                    namespace = 'main', 
                    progress_mode = 'count', 
                    team_id = '', ),
                type = 'update'
            )
        else:
            return WorkspaceBulkUpdate(
                id = '',
                resource = openapi_client.models.workspace.Workspace(
                    alias = '', 
                    archived = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    default_permission = 'comment', 
                    description = openapi_client.models.rich_text.RichText(
                        blocks = [
                            null
                            ], ), 
                    id = '', 
                    item_color = 'amber', 
                    item_type = 'bug', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    legacy_id = '', 
                    metadata = openapi_client.models.workspace_workspace_metadata.WorkspaceWorkspaceMetadata(
                        duplicated = True, 
                        template_id = '', 
                        template_workspace_ref = '', 
                        version = '', ), 
                    name = '', 
                    namespace = 'main', 
                    progress_mode = 'count', 
                    team_id = '', ),
                type = 'update',
        )
        """

    def testWorkspaceBulkUpdate(self):
        """Test WorkspaceBulkUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
