# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rich_text_inline_link import RichTextInlineLink

class TestRichTextInlineLink(unittest.TestCase):
    """RichTextInlineLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RichTextInlineLink:
        """Test RichTextInlineLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RichTextInlineLink`
        """
        model = RichTextInlineLink()
        if include_optional:
            return RichTextInlineLink(
                content = None,
                url = ''
            )
        else:
            return RichTextInlineLink(
                content = None,
                url = '',
        )
        """

    def testRichTextInlineLink(self):
        """Test RichTextInlineLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
