# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_color import ItemColor

class TestItemColor(unittest.TestCase):
    """ItemColor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemColor(self):
        """Test ItemColor"""
        # inst = ItemColor()

if __name__ == '__main__':
    unittest.main()
