# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_group_with_workspace_group_embed_page import WorkspaceGroupWithWorkspaceGroupEmbedPage

class TestWorkspaceGroupWithWorkspaceGroupEmbedPage(unittest.TestCase):
    """WorkspaceGroupWithWorkspaceGroupEmbedPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGroupWithWorkspaceGroupEmbedPage:
        """Test WorkspaceGroupWithWorkspaceGroupEmbedPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGroupWithWorkspaceGroupEmbedPage`
        """
        model = WorkspaceGroupWithWorkspaceGroupEmbedPage()
        if include_optional:
            return WorkspaceGroupWithWorkspaceGroupEmbedPage(
                items = [
                    openapi_client.models.workspace_group_with_workspace_group_embed.WorkspaceGroupWithWorkspaceGroupEmbed(
                        _embedded = openapi_client.models.workspace_group_embed.WorkspaceGroupEmbed(
                            current_permission = 'comment', 
                            permissions = {
                                'key' : 'comment'
                                }, 
                            workspaces = [
                                openapi_client.models.workspace.Workspace(
                                    alias = '', 
                                    archived = True, 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    default_permission = 'comment', 
                                    description = openapi_client.models.rich_text.RichText(
                                        blocks = [
                                            null
                                            ], ), 
                                    id = '', 
                                    item_color = 'amber', 
                                    item_type = 'bug', 
                                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    legacy_id = '', 
                                    metadata = openapi_client.models.workspace_workspace_metadata.WorkspaceWorkspaceMetadata(
                                        duplicated = True, 
                                        template_id = '', 
                                        template_workspace_ref = '', 
                                        version = '', ), 
                                    name = '', 
                                    namespace = 'main', 
                                    progress_mode = 'count', 
                                    team_id = '', )
                                ], ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        default_permission = 'comment', 
                        id = '', 
                        last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        team_id = '', )
                    ],
                total_items = 56
            )
        else:
            return WorkspaceGroupWithWorkspaceGroupEmbedPage(
                total_items = 56,
        )
        """

    def testWorkspaceGroupWithWorkspaceGroupEmbedPage(self):
        """Test WorkspaceGroupWithWorkspaceGroupEmbedPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
