# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.team_state import TeamState

class TestTeamState(unittest.TestCase):
    """TeamState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamState:
        """Test TeamState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamState`
        """
        model = TeamState()
        if include_optional:
            return TeamState(
                features = [
                    ''
                    ],
                seats = openapi_client.models.team_state_all_team_state_seats.TeamStateAllTeamStateSeats(
                    admin = openapi_client.models.team_state_seats.TeamStateSeats(
                        free = 56, 
                        total = 56, 
                        used = 56, ), 
                    any = openapi_client.models.team_state_seats.TeamStateSeats(
                        free = 56, 
                        total = 56, 
                        used = 56, ), 
                    contributor = , 
                    editor = , ),
                subscription = None,
                trial_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                workspaces = openapi_client.models.team_state_workspaces.TeamStateWorkspaces(
                    total = 56, )
            )
        else:
            return TeamState(
                features = [
                    ''
                    ],
                seats = openapi_client.models.team_state_all_team_state_seats.TeamStateAllTeamStateSeats(
                    admin = openapi_client.models.team_state_seats.TeamStateSeats(
                        free = 56, 
                        total = 56, 
                        used = 56, ), 
                    any = openapi_client.models.team_state_seats.TeamStateSeats(
                        free = 56, 
                        total = 56, 
                        used = 56, ), 
                    contributor = , 
                    editor = , ),
                subscription = None,
                workspaces = openapi_client.models.team_state_workspaces.TeamStateWorkspaces(
                    total = 56, ),
        )
        """

    def testTeamState(self):
        """Test TeamState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
