# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.view import View

class TestView(unittest.TestCase):
    """View unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> View:
        """Test View
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `View`
        """
        model = View()
        if include_optional:
            return View(
                description = '',
                id = '',
                item_filter = None,
                item_sort = [
                    null
                    ],
                name = '',
                order = 56,
                pinned_to_position = 56,
                private_owner_id = '',
                required_permission = 'comment',
                settings = None,
                type_id = '',
                workspace_id = ''
            )
        else:
            return View(
                description = '',
                id = '',
                name = '',
                order = 56,
                settings = None,
                type_id = '',
                workspace_id = '',
        )
        """

    def testView(self):
        """Test View"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
