# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.number_field_type_settings_stepping_exponential import NumberFieldTypeSettingsSteppingExponential

class TestNumberFieldTypeSettingsSteppingExponential(unittest.TestCase):
    """NumberFieldTypeSettingsSteppingExponential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumberFieldTypeSettingsSteppingExponential:
        """Test NumberFieldTypeSettingsSteppingExponential
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumberFieldTypeSettingsSteppingExponential`
        """
        model = NumberFieldTypeSettingsSteppingExponential()
        if include_optional:
            return NumberFieldTypeSettingsSteppingExponential(
                factor = 1.337
            )
        else:
            return NumberFieldTypeSettingsSteppingExponential(
                factor = 1.337,
        )
        """

    def testNumberFieldTypeSettingsSteppingExponential(self):
        """Test NumberFieldTypeSettingsSteppingExponential"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
