# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_relation_with_embed_page import ItemRelationWithEmbedPage

class TestItemRelationWithEmbedPage(unittest.TestCase):
    """ItemRelationWithEmbedPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemRelationWithEmbedPage:
        """Test ItemRelationWithEmbedPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemRelationWithEmbedPage`
        """
        model = ItemRelationWithEmbedPage()
        if include_optional:
            return ItemRelationWithEmbedPage(
                items = [
                    openapi_client.models.item_relation_with_embed.ItemRelationWithEmbed(
                        _embedded = openapi_client.models._embedded._embedded(), 
                        child_id = '', 
                        child_order = 56, 
                        id = '', 
                        parent_id = '', 
                        parent_order = 56, )
                    ],
                total_items = 56
            )
        else:
            return ItemRelationWithEmbedPage(
                total_items = 56,
        )
        """

    def testItemRelationWithEmbedPage(self):
        """Test ItemRelationWithEmbedPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
