# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.item_links_api import ItemLinksApi


class TestItemLinksApi(unittest.TestCase):
    """ItemLinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemLinksApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_item_links(self) -> None:
        """Test case for bulk_item_links

        Perform multiple operations with item links
        """
        pass

    def test_create_item_link(self) -> None:
        """Test case for create_item_link

        Create a new item link
        """
        pass

    def test_delete_item_link(self) -> None:
        """Test case for delete_item_link

        Delete an existing item link
        """
        pass

    def test_list_item_links(self) -> None:
        """Test case for list_item_links

        Retrieve multiple item links by their IDs
        """
        pass

    def test_patch_item_link(self) -> None:
        """Test case for patch_item_link

        Patch an existing item link
        """
        pass

    def test_retrieve_item_link(self) -> None:
        """Test case for retrieve_item_link

        Retrieve a single item link by its ID
        """
        pass

    def test_search_item_links(self) -> None:
        """Test case for search_item_links

        Retrieve or search item links
        """
        pass

    def test_update_item_link(self) -> None:
        """Test case for update_item_link

        Update an existing item link
        """
        pass


if __name__ == '__main__':
    unittest.main()
