# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.template_page_with_embed import TemplatePageWithEmbed

class TestTemplatePageWithEmbed(unittest.TestCase):
    """TemplatePageWithEmbed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatePageWithEmbed:
        """Test TemplatePageWithEmbed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatePageWithEmbed`
        """
        model = TemplatePageWithEmbed()
        if include_optional:
            return TemplatePageWithEmbed(
                embedded = openapi_client.models.template_search_embed.TemplateSearchEmbed(
                    categories = [
                        openapi_client.models.template_category.TemplateCategory(
                            name = '', 
                            slug = '', 
                            template_ids = [
                                ''
                                ], )
                        ], ),
                items = [
                    openapi_client.models.template.Template(
                        abstract = '', 
                        apps = [
                            openapi_client.models.template_app.TemplateApp(
                                description = '', 
                                name = '', 
                                type_id = '', )
                            ], 
                        description = '', 
                        featured = True, 
                        id = '', 
                        image_url = '', 
                        name = '', 
                        views = [
                            openapi_client.models.template_view.TemplateView(
                                description = '', 
                                icon_name = '', 
                                image_url = '', 
                                name = '', )
                            ], 
                        views_section_title = '', 
                        workspaces_count = 56, )
                    ],
                total_items = 56
            )
        else:
            return TemplatePageWithEmbed(
                embedded = openapi_client.models.template_search_embed.TemplateSearchEmbed(
                    categories = [
                        openapi_client.models.template_category.TemplateCategory(
                            name = '', 
                            slug = '', 
                            template_ids = [
                                ''
                                ], )
                        ], ),
                total_items = 56,
        )
        """

    def testTemplatePageWithEmbed(self):
        """Test TemplatePageWithEmbed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
