# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_items(self) -> None:
        """Test case for bulk_items

        Perform multiple operations with items
        """
        pass

    def test_copy_items(self) -> None:
        """Test case for copy_items

        Copy specified items.
        """
        pass

    def test_create_item(self) -> None:
        """Test case for create_item

        Create a new item
        """
        pass

    def test_delete_item(self) -> None:
        """Test case for delete_item

        Delete an existing item
        """
        pass

    def test_list_items(self) -> None:
        """Test case for list_items

        Retrieve multiple items by their IDs
        """
        pass

    def test_move_items(self) -> None:
        """Test case for move_items

        Move specified items from one workspace to another.
        """
        pass

    def test_patch_item(self) -> None:
        """Test case for patch_item

        Patch an existing item
        """
        pass

    def test_reset_item_colors(self) -> None:
        """Test case for reset_item_colors

        Reset colors of all items in the specified workspace.
        """
        pass

    def test_retrieve_item(self) -> None:
        """Test case for retrieve_item

        Retrieve a single item by its ID
        """
        pass

    def test_retrieve_item_by_alias(self) -> None:
        """Test case for retrieve_item_by_alias

        Retrieve a single item by its alias (e.g. 'DEV-123').
        """
        pass

    def test_retrieve_items_globally(self) -> None:
        """Test case for retrieve_items_globally

        Retrieve items from any workspace by specified IDs.
        """
        pass

    def test_search_items(self) -> None:
        """Test case for search_items

        Retrieve or search items
        """
        pass

    def test_unwatch_items(self) -> None:
        """Test case for unwatch_items

        Remove watching status of the current user for the specified items.
        """
        pass

    def test_update_item(self) -> None:
        """Test case for update_item

        Update an existing item
        """
        pass

    def test_watch_items(self) -> None:
        """Test case for watch_items

        Set current user as a watcher of the specified items.
        """
        pass


if __name__ == '__main__':
    unittest.main()
