# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.team_api import TeamApi


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamApi()

    def tearDown(self) -> None:
        pass

    def test_accept_terms_of_service(self) -> None:
        """Test case for accept_terms_of_service

        """
        pass

    def test_change_user_disabled(self) -> None:
        """Test case for change_user_disabled

        """
        pass

    def test_change_user_role(self) -> None:
        """Test case for change_user_role

        """
        pass

    def test_create_user_invite(self) -> None:
        """Test case for create_user_invite

        """
        pass

    def test_kick_user(self) -> None:
        """Test case for kick_user

        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        """
        pass

    def test_resend_user_invite(self) -> None:
        """Test case for resend_user_invite

        """
        pass

    def test_retrieve_team(self) -> None:
        """Test case for retrieve_team

        """
        pass

    def test_send_bulk_user_invites(self) -> None:
        """Test case for send_bulk_user_invites

        """
        pass

    def test_send_user_invite(self) -> None:
        """Test case for send_user_invite

        """
        pass

    def test_update_team_flags(self) -> None:
        """Test case for update_team_flags

        """
        pass


if __name__ == '__main__':
    unittest.main()
