# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.team_company_info_size import TeamCompanyInfoSize

class TestTeamCompanyInfoSize(unittest.TestCase):
    """TeamCompanyInfoSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamCompanyInfoSize(self):
        """Test TeamCompanyInfoSize"""
        # inst = TeamCompanyInfoSize()

if __name__ == '__main__':
    unittest.main()
