# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_attachment_with_embed_page import ItemAttachmentWithEmbedPage

class TestItemAttachmentWithEmbedPage(unittest.TestCase):
    """ItemAttachmentWithEmbedPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemAttachmentWithEmbedPage:
        """Test ItemAttachmentWithEmbedPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemAttachmentWithEmbedPage`
        """
        model = ItemAttachmentWithEmbedPage()
        if include_optional:
            return ItemAttachmentWithEmbedPage(
                items = [
                    openapi_client.models.item_attachment_with_embed.ItemAttachmentWithEmbed(
                        _embedded = openapi_client.models._embedded._embedded(), 
                        content_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        item_id = '', 
                        last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        uri = '', )
                    ],
                total_items = 56
            )
        else:
            return ItemAttachmentWithEmbedPage(
                total_items = 56,
        )
        """

    def testItemAttachmentWithEmbedPage(self):
        """Test ItemAttachmentWithEmbedPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
