# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_search_query_filter_created_at import ItemSearchQueryFilterCreatedAt

class TestItemSearchQueryFilterCreatedAt(unittest.TestCase):
    """ItemSearchQueryFilterCreatedAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemSearchQueryFilterCreatedAt:
        """Test ItemSearchQueryFilterCreatedAt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemSearchQueryFilterCreatedAt`
        """
        model = ItemSearchQueryFilterCreatedAt()
        if include_optional:
            return ItemSearchQueryFilterCreatedAt(
                mode = 'after',
                value = openapi_client.models.item_search_query_date_time_filter_value.ItemSearchQueryDateTimeFilterValue(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    time = '', 
                    zone_id = '', )
            )
        else:
            return ItemSearchQueryFilterCreatedAt(
                mode = 'after',
                value = openapi_client.models.item_search_query_date_time_filter_value.ItemSearchQueryDateTimeFilterValue(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    time = '', 
                    zone_id = '', ),
        )
        """

    def testItemSearchQueryFilterCreatedAt(self):
        """Test ItemSearchQueryFilterCreatedAt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
