# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentsApi()

    def tearDown(self) -> None:
        pass

    def test_add_comment_reaction(self) -> None:
        """Test case for add_comment_reaction

        Add a reaction to the specified comment.
        """
        pass

    def test_bulk_comments(self) -> None:
        """Test case for bulk_comments

        Perform multiple operations with comments
        """
        pass

    def test_create_comment(self) -> None:
        """Test case for create_comment

        Create a new comment
        """
        pass

    def test_delete_comment(self) -> None:
        """Test case for delete_comment

        Delete an existing comment
        """
        pass

    def test_list_comments(self) -> None:
        """Test case for list_comments

        Retrieve multiple comments by their IDs
        """
        pass

    def test_patch_comment(self) -> None:
        """Test case for patch_comment

        Patch an existing comment
        """
        pass

    def test_remove_comment_reaction(self) -> None:
        """Test case for remove_comment_reaction

        Remove a reaction from the specified comment.
        """
        pass

    def test_retrieve_comment(self) -> None:
        """Test case for retrieve_comment

        Retrieve a single comment by its ID
        """
        pass

    def test_search_comments(self) -> None:
        """Test case for search_comments

        Retrieve or search comments
        """
        pass

    def test_update_comment(self) -> None:
        """Test case for update_comment

        Update an existing comment
        """
        pass


if __name__ == '__main__':
    unittest.main()
