# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_attachment_bulk_action import ItemAttachmentBulkAction

class TestItemAttachmentBulkAction(unittest.TestCase):
    """ItemAttachmentBulkAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemAttachmentBulkAction:
        """Test ItemAttachmentBulkAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemAttachmentBulkAction`
        """
        model = ItemAttachmentBulkAction()
        if include_optional:
            return ItemAttachmentBulkAction(
                resource = openapi_client.models.item_attachment.ItemAttachment(
                    content_type = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    item_id = '', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    uri = '', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ]
            )
        else:
            return ItemAttachmentBulkAction(
                resource = openapi_client.models.item_attachment.ItemAttachment(
                    content_type = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    item_id = '', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    uri = '', ),
                type = 'create',
                id = '',
                transform = [
                    null
                    ],
        )
        """

    def testItemAttachmentBulkAction(self):
        """Test ItemAttachmentBulkAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
