# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.milestone_with_embed import MilestoneWithEmbed

class TestMilestoneWithEmbed(unittest.TestCase):
    """MilestoneWithEmbed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneWithEmbed:
        """Test MilestoneWithEmbed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneWithEmbed`
        """
        model = MilestoneWithEmbed()
        if include_optional:
            return MilestoneWithEmbed(
                embedded = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                description = '',
                id = '',
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                timezone = '',
                workspace_id = ''
            )
        else:
            return MilestoneWithEmbed(
                embedded = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                description = '',
                id = '',
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                workspace_id = '',
        )
        """

    def testMilestoneWithEmbed(self):
        """Test MilestoneWithEmbed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
