# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_search_query_sort_direction import ItemSearchQuerySortDirection

class TestItemSearchQuerySortDirection(unittest.TestCase):
    """ItemSearchQuerySortDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemSearchQuerySortDirection(self):
        """Test ItemSearchQuerySortDirection"""
        # inst = ItemSearchQuerySortDirection()

if __name__ == '__main__':
    unittest.main()
