# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.milestone_bulk_create import MilestoneBulkCreate

class TestMilestoneBulkCreate(unittest.TestCase):
    """MilestoneBulkCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneBulkCreate:
        """Test MilestoneBulkCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneBulkCreate`
        """
        model = MilestoneBulkCreate()
        if include_optional:
            return MilestoneBulkCreate(
                resource = openapi_client.models.milestone.Milestone(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    id = '', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    timezone = '', 
                    workspace_id = '', ),
                type = 'create'
            )
        else:
            return MilestoneBulkCreate(
                resource = openapi_client.models.milestone.Milestone(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    description = '', 
                    id = '', 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    timezone = '', 
                    workspace_id = '', ),
                type = 'create',
        )
        """

    def testMilestoneBulkCreate(self):
        """Test MilestoneBulkCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
