# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.item_attachment_bulk_create import ItemAttachmentBulkCreate
from openapi_client.models.item_attachment_bulk_delete import ItemAttachmentBulkDelete
from openapi_client.models.item_attachment_bulk_patch import ItemAttachmentBulkPatch
from openapi_client.models.item_attachment_bulk_update import ItemAttachmentBulkUpdate
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ITEMATTACHMENTBULKACTION_ONE_OF_SCHEMAS = ["ItemAttachmentBulkCreate", "ItemAttachmentBulkDelete", "ItemAttachmentBulkPatch", "ItemAttachmentBulkUpdate"]

class ItemAttachmentBulkAction(BaseModel):
    """
    ItemAttachmentBulkAction
    """
    # data type: ItemAttachmentBulkCreate
    oneof_schema_1_validator: Optional[ItemAttachmentBulkCreate] = None
    # data type: ItemAttachmentBulkDelete
    oneof_schema_2_validator: Optional[ItemAttachmentBulkDelete] = None
    # data type: ItemAttachmentBulkPatch
    oneof_schema_3_validator: Optional[ItemAttachmentBulkPatch] = None
    # data type: ItemAttachmentBulkUpdate
    oneof_schema_4_validator: Optional[ItemAttachmentBulkUpdate] = None
    actual_instance: Optional[Union[ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate]] = None
    one_of_schemas: Set[str] = { "ItemAttachmentBulkCreate", "ItemAttachmentBulkDelete", "ItemAttachmentBulkPatch", "ItemAttachmentBulkUpdate" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ItemAttachmentBulkAction.model_construct()
        error_messages = []
        match = 0
        # validate data type: ItemAttachmentBulkCreate
        if not isinstance(v, ItemAttachmentBulkCreate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemAttachmentBulkCreate`")
        else:
            match += 1
        # validate data type: ItemAttachmentBulkDelete
        if not isinstance(v, ItemAttachmentBulkDelete):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemAttachmentBulkDelete`")
        else:
            match += 1
        # validate data type: ItemAttachmentBulkPatch
        if not isinstance(v, ItemAttachmentBulkPatch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemAttachmentBulkPatch`")
        else:
            match += 1
        # validate data type: ItemAttachmentBulkUpdate
        if not isinstance(v, ItemAttachmentBulkUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemAttachmentBulkUpdate`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ItemAttachmentBulkAction with oneOf schemas: ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ItemAttachmentBulkAction with oneOf schemas: ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ItemAttachmentBulkCreate
        try:
            instance.actual_instance = ItemAttachmentBulkCreate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemAttachmentBulkDelete
        try:
            instance.actual_instance = ItemAttachmentBulkDelete.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemAttachmentBulkPatch
        try:
            instance.actual_instance = ItemAttachmentBulkPatch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemAttachmentBulkUpdate
        try:
            instance.actual_instance = ItemAttachmentBulkUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ItemAttachmentBulkAction with oneOf schemas: ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ItemAttachmentBulkAction with oneOf schemas: ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ItemAttachmentBulkCreate, ItemAttachmentBulkDelete, ItemAttachmentBulkPatch, ItemAttachmentBulkUpdate]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


