# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.item_search_query_sort_created_at import ItemSearchQuerySortCreatedAt
from openapi_client.models.item_search_query_sort_field import ItemSearchQuerySortField
from openapi_client.models.item_search_query_sort_last_updated_at import ItemSearchQuerySortLastUpdatedAt
from openapi_client.models.item_search_query_sort_name import ItemSearchQuerySortName
from openapi_client.models.item_search_query_sort_order import ItemSearchQuerySortOrder
from openapi_client.models.item_search_query_sort_status import ItemSearchQuerySortStatus
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ITEMSEARCHQUERYSORT_ONE_OF_SCHEMAS = ["ItemSearchQuerySortCreatedAt", "ItemSearchQuerySortField", "ItemSearchQuerySortLastUpdatedAt", "ItemSearchQuerySortName", "ItemSearchQuerySortOrder", "ItemSearchQuerySortStatus"]

class ItemSearchQuerySort(BaseModel):
    """
    ItemSearchQuerySort
    """
    # data type: ItemSearchQuerySortCreatedAt
    oneof_schema_1_validator: Optional[ItemSearchQuerySortCreatedAt] = None
    # data type: ItemSearchQuerySortField
    oneof_schema_2_validator: Optional[ItemSearchQuerySortField] = None
    # data type: ItemSearchQuerySortLastUpdatedAt
    oneof_schema_3_validator: Optional[ItemSearchQuerySortLastUpdatedAt] = None
    # data type: ItemSearchQuerySortName
    oneof_schema_4_validator: Optional[ItemSearchQuerySortName] = None
    # data type: ItemSearchQuerySortOrder
    oneof_schema_5_validator: Optional[ItemSearchQuerySortOrder] = None
    # data type: ItemSearchQuerySortStatus
    oneof_schema_6_validator: Optional[ItemSearchQuerySortStatus] = None
    actual_instance: Optional[Union[ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus]] = None
    one_of_schemas: Set[str] = { "ItemSearchQuerySortCreatedAt", "ItemSearchQuerySortField", "ItemSearchQuerySortLastUpdatedAt", "ItemSearchQuerySortName", "ItemSearchQuerySortOrder", "ItemSearchQuerySortStatus" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ItemSearchQuerySort.model_construct()
        error_messages = []
        match = 0
        # validate data type: ItemSearchQuerySortCreatedAt
        if not isinstance(v, ItemSearchQuerySortCreatedAt):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortCreatedAt`")
        else:
            match += 1
        # validate data type: ItemSearchQuerySortField
        if not isinstance(v, ItemSearchQuerySortField):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortField`")
        else:
            match += 1
        # validate data type: ItemSearchQuerySortLastUpdatedAt
        if not isinstance(v, ItemSearchQuerySortLastUpdatedAt):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortLastUpdatedAt`")
        else:
            match += 1
        # validate data type: ItemSearchQuerySortName
        if not isinstance(v, ItemSearchQuerySortName):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortName`")
        else:
            match += 1
        # validate data type: ItemSearchQuerySortOrder
        if not isinstance(v, ItemSearchQuerySortOrder):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortOrder`")
        else:
            match += 1
        # validate data type: ItemSearchQuerySortStatus
        if not isinstance(v, ItemSearchQuerySortStatus):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQuerySortStatus`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ItemSearchQuerySort with oneOf schemas: ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ItemSearchQuerySort with oneOf schemas: ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ItemSearchQuerySortCreatedAt
        try:
            instance.actual_instance = ItemSearchQuerySortCreatedAt.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQuerySortField
        try:
            instance.actual_instance = ItemSearchQuerySortField.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQuerySortLastUpdatedAt
        try:
            instance.actual_instance = ItemSearchQuerySortLastUpdatedAt.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQuerySortName
        try:
            instance.actual_instance = ItemSearchQuerySortName.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQuerySortOrder
        try:
            instance.actual_instance = ItemSearchQuerySortOrder.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQuerySortStatus
        try:
            instance.actual_instance = ItemSearchQuerySortStatus.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ItemSearchQuerySort with oneOf schemas: ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ItemSearchQuerySort with oneOf schemas: ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ItemSearchQuerySortCreatedAt, ItemSearchQuerySortField, ItemSearchQuerySortLastUpdatedAt, ItemSearchQuerySortName, ItemSearchQuerySortOrder, ItemSearchQuerySortStatus]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


