# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from openapi_client.models.item_search_query_filter_assignees_contain import ItemSearchQueryFilterAssigneesContain
from openapi_client.models.item_search_query_filter_assignees_contains_all import ItemSearchQueryFilterAssigneesContainsAll
from openapi_client.models.item_search_query_filter_assignees_contains_any import ItemSearchQueryFilterAssigneesContainsAny
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ITEMSEARCHQUERYFILTERASSIGNEES_ONE_OF_SCHEMAS = ["ItemSearchQueryFilterAssigneesContain", "ItemSearchQueryFilterAssigneesContainsAll", "ItemSearchQueryFilterAssigneesContainsAny", "object"]

class ItemSearchQueryFilterAssignees(BaseModel):
    """
    ItemSearchQueryFilterAssignees
    """
    # data type: ItemSearchQueryFilterAssigneesContain
    oneof_schema_1_validator: Optional[ItemSearchQueryFilterAssigneesContain] = None
    # data type: ItemSearchQueryFilterAssigneesContainsAll
    oneof_schema_2_validator: Optional[ItemSearchQueryFilterAssigneesContainsAll] = None
    # data type: ItemSearchQueryFilterAssigneesContainsAny
    oneof_schema_3_validator: Optional[ItemSearchQueryFilterAssigneesContainsAny] = None
    # data type: object
    oneof_schema_4_validator: Optional[Dict[str, Any]] = None
    actual_instance: Optional[Union[ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object]] = None
    one_of_schemas: Set[str] = { "ItemSearchQueryFilterAssigneesContain", "ItemSearchQueryFilterAssigneesContainsAll", "ItemSearchQueryFilterAssigneesContainsAny", "object" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ItemSearchQueryFilterAssignees.model_construct()
        error_messages = []
        match = 0
        # validate data type: ItemSearchQueryFilterAssigneesContain
        if not isinstance(v, ItemSearchQueryFilterAssigneesContain):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQueryFilterAssigneesContain`")
        else:
            match += 1
        # validate data type: ItemSearchQueryFilterAssigneesContainsAll
        if not isinstance(v, ItemSearchQueryFilterAssigneesContainsAll):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQueryFilterAssigneesContainsAll`")
        else:
            match += 1
        # validate data type: ItemSearchQueryFilterAssigneesContainsAny
        if not isinstance(v, ItemSearchQueryFilterAssigneesContainsAny):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemSearchQueryFilterAssigneesContainsAny`")
        else:
            match += 1
        # validate data type: object
        try:
            instance.oneof_schema_4_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ItemSearchQueryFilterAssignees with oneOf schemas: ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ItemSearchQueryFilterAssignees with oneOf schemas: ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ItemSearchQueryFilterAssigneesContain
        try:
            instance.actual_instance = ItemSearchQueryFilterAssigneesContain.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQueryFilterAssigneesContainsAll
        try:
            instance.actual_instance = ItemSearchQueryFilterAssigneesContainsAll.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemSearchQueryFilterAssigneesContainsAny
        try:
            instance.actual_instance = ItemSearchQueryFilterAssigneesContainsAny.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_4_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_4_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ItemSearchQueryFilterAssignees with oneOf schemas: ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ItemSearchQueryFilterAssignees with oneOf schemas: ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ItemSearchQueryFilterAssigneesContain, ItemSearchQueryFilterAssigneesContainsAll, ItemSearchQueryFilterAssigneesContainsAny, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


