# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ItemType(str, Enum):
    """
    ItemType
    """

    """
    allowed enum values
    """
    BUG = 'bug'
    EPIC = 'epic'
    EXPERIMENT = 'experiment'
    FEATURE = 'feature'
    FEEDBACK = 'feedback'
    IDEA = 'idea'
    INITIATIVE = 'initiative'
    APP_COLON_OKR_COLON_OBJECTIVE = 'app:okr:objective'
    OPPORTUNITY = 'opportunity'
    PRODUCT = 'product'
    PROJECT = 'project'
    STORY = 'story'
    TASK = 'task'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ItemType from a JSON string"""
        return cls(json.loads(json_str))


