# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MilestoneWithEmbed(BaseModel):
    """
    MilestoneWithEmbed
    """ # noqa: E501
    embedded: Dict[str, Any] = Field(alias="_embedded")
    created_at: datetime = Field(alias="createdAt")
    var_date: date = Field(alias="date")
    description: StrictStr
    id: StrictStr
    last_updated_at: datetime = Field(alias="lastUpdatedAt")
    name: StrictStr
    timezone: Optional[StrictStr] = None
    workspace_id: StrictStr = Field(alias="workspaceId")
    __properties: ClassVar[List[str]] = ["_embedded", "createdAt", "date", "description", "id", "lastUpdatedAt", "name", "timezone", "workspaceId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MilestoneWithEmbed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MilestoneWithEmbed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_embedded": obj.get("_embedded"),
            "createdAt": obj.get("createdAt"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "lastUpdatedAt": obj.get("lastUpdatedAt"),
            "name": obj.get("name"),
            "timezone": obj.get("timezone"),
            "workspaceId": obj.get("workspaceId")
        })
        return _obj


