# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.number_field_type_settings_stepping import NumberFieldTypeSettingsStepping
from openapi_client.models.number_field_type_settings_unit import NumberFieldTypeSettingsUnit
from typing import Optional, Set
from typing_extensions import Self

class NumberFieldTypeSettings(BaseModel):
    """
    NumberFieldTypeSettings
    """ # noqa: E501
    maximum: Optional[Union[StrictFloat, StrictInt]] = None
    minimum: Optional[Union[StrictFloat, StrictInt]] = None
    overflow: StrictBool
    stepping: Optional[NumberFieldTypeSettingsStepping] = None
    unit: Optional[NumberFieldTypeSettingsUnit] = None
    __properties: ClassVar[List[str]] = ["maximum", "minimum", "overflow", "stepping", "unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NumberFieldTypeSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of stepping
        if self.stepping:
            _dict['stepping'] = self.stepping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unit
        if self.unit:
            _dict['unit'] = self.unit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NumberFieldTypeSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maximum": obj.get("maximum"),
            "minimum": obj.get("minimum"),
            "overflow": obj.get("overflow"),
            "stepping": NumberFieldTypeSettingsStepping.from_dict(obj["stepping"]) if obj.get("stepping") is not None else None,
            "unit": NumberFieldTypeSettingsUnit.from_dict(obj["unit"]) if obj.get("unit") is not None else None
        })
        return _obj


