# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatusColor(str, Enum):
    """
    Color of a status-chip in UI.
    """

    """
    allowed enum values
    """
    BLUE = 'blue'
    COCO = 'coco'
    DAULPHINE = 'daulphine'
    GREAT = 'great'
    ORANGE = 'orange'
    PINK = 'pink'
    RED = 'red'
    VIOLET = 'violet'
    YELLOW = 'yellow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatusColor from a JSON string"""
        return cls(json.loads(json_str))


