# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.team_state_seats import TeamStateSeats
from typing import Optional, Set
from typing_extensions import Self

class TeamStateAllTeamStateSeats(BaseModel):
    """
    TeamStateAllTeamStateSeats
    """ # noqa: E501
    admin: Optional[TeamStateSeats] = None
    any: Optional[TeamStateSeats] = None
    contributor: Optional[TeamStateSeats] = None
    editor: Optional[TeamStateSeats] = None
    __properties: ClassVar[List[str]] = ["admin", "any", "contributor", "editor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TeamStateAllTeamStateSeats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of admin
        if self.admin:
            _dict['admin'] = self.admin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of any
        if self.any:
            _dict['any'] = self.any.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contributor
        if self.contributor:
            _dict['contributor'] = self.contributor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of editor
        if self.editor:
            _dict['editor'] = self.editor.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TeamStateAllTeamStateSeats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "admin": TeamStateSeats.from_dict(obj["admin"]) if obj.get("admin") is not None else None,
            "any": TeamStateSeats.from_dict(obj["any"]) if obj.get("any") is not None else None,
            "contributor": TeamStateSeats.from_dict(obj["contributor"]) if obj.get("contributor") is not None else None,
            "editor": TeamStateSeats.from_dict(obj["editor"]) if obj.get("editor") is not None else None
        })
        return _obj


