# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TeamCompanyInfoSize(str, Enum):
    """
    TeamCompanyInfoSize
    """

    """
    allowed enum values
    """
    RANGE1000PLUS = 'range1000plus'
    RANGE11TO50 = 'range11to50'
    RANGE1TO10 = 'range1to10'
    RANGE201TO1000 = 'range201to1000'
    RANGE51TO200 = 'range51to200'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TeamCompanyInfoSize from a JSON string"""
        return cls(json.loads(json_str))


