# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.workspace_group_bulk_create import WorkspaceGroupBulkCreate
from openapi_client.models.workspace_group_bulk_delete import WorkspaceGroupBulkDelete
from openapi_client.models.workspace_group_bulk_patch import WorkspaceGroupBulkPatch
from openapi_client.models.workspace_group_bulk_update import WorkspaceGroupBulkUpdate
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WORKSPACEGROUPBULKACTION_ONE_OF_SCHEMAS = ["WorkspaceGroupBulkCreate", "WorkspaceGroupBulkDelete", "WorkspaceGroupBulkPatch", "WorkspaceGroupBulkUpdate"]

class WorkspaceGroupBulkAction(BaseModel):
    """
    WorkspaceGroupBulkAction
    """
    # data type: WorkspaceGroupBulkCreate
    oneof_schema_1_validator: Optional[WorkspaceGroupBulkCreate] = None
    # data type: WorkspaceGroupBulkDelete
    oneof_schema_2_validator: Optional[WorkspaceGroupBulkDelete] = None
    # data type: WorkspaceGroupBulkPatch
    oneof_schema_3_validator: Optional[WorkspaceGroupBulkPatch] = None
    # data type: WorkspaceGroupBulkUpdate
    oneof_schema_4_validator: Optional[WorkspaceGroupBulkUpdate] = None
    actual_instance: Optional[Union[WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate]] = None
    one_of_schemas: Set[str] = { "WorkspaceGroupBulkCreate", "WorkspaceGroupBulkDelete", "WorkspaceGroupBulkPatch", "WorkspaceGroupBulkUpdate" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WorkspaceGroupBulkAction.model_construct()
        error_messages = []
        match = 0
        # validate data type: WorkspaceGroupBulkCreate
        if not isinstance(v, WorkspaceGroupBulkCreate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceGroupBulkCreate`")
        else:
            match += 1
        # validate data type: WorkspaceGroupBulkDelete
        if not isinstance(v, WorkspaceGroupBulkDelete):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceGroupBulkDelete`")
        else:
            match += 1
        # validate data type: WorkspaceGroupBulkPatch
        if not isinstance(v, WorkspaceGroupBulkPatch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceGroupBulkPatch`")
        else:
            match += 1
        # validate data type: WorkspaceGroupBulkUpdate
        if not isinstance(v, WorkspaceGroupBulkUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceGroupBulkUpdate`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WorkspaceGroupBulkAction with oneOf schemas: WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WorkspaceGroupBulkAction with oneOf schemas: WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into WorkspaceGroupBulkCreate
        try:
            instance.actual_instance = WorkspaceGroupBulkCreate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceGroupBulkDelete
        try:
            instance.actual_instance = WorkspaceGroupBulkDelete.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceGroupBulkPatch
        try:
            instance.actual_instance = WorkspaceGroupBulkPatch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceGroupBulkUpdate
        try:
            instance.actual_instance = WorkspaceGroupBulkUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WorkspaceGroupBulkAction with oneOf schemas: WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WorkspaceGroupBulkAction with oneOf schemas: WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], WorkspaceGroupBulkCreate, WorkspaceGroupBulkDelete, WorkspaceGroupBulkPatch, WorkspaceGroupBulkUpdate]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


