# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.workspace_search_query_filter_members_contain_any import WorkspaceSearchQueryFilterMembersContainAny
from openapi_client.models.workspace_search_query_filter_name_contain import WorkspaceSearchQueryFilterNameContain
from openapi_client.models.workspace_search_query_filter_name_equal import WorkspaceSearchQueryFilterNameEqual
from openapi_client.models.workspace_search_query_filter_namespace_contain_any import WorkspaceSearchQueryFilterNamespaceContainAny
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WORKSPACESEARCHQUERYFILTER_ONE_OF_SCHEMAS = ["WorkspaceSearchQueryFilterAnd", "WorkspaceSearchQueryFilterMembersContainAny", "WorkspaceSearchQueryFilterNameContain", "WorkspaceSearchQueryFilterNameEqual", "WorkspaceSearchQueryFilterNamespaceContainAny", "WorkspaceSearchQueryFilterNot", "WorkspaceSearchQueryFilterOr"]

class WorkspaceSearchQueryFilter(BaseModel):
    """
    WorkspaceSearchQueryFilter
    """
    # data type: WorkspaceSearchQueryFilterAnd
    oneof_schema_1_validator: Optional[WorkspaceSearchQueryFilterAnd] = None
    # data type: WorkspaceSearchQueryFilterMembersContainAny
    oneof_schema_2_validator: Optional[WorkspaceSearchQueryFilterMembersContainAny] = None
    # data type: WorkspaceSearchQueryFilterNameContain
    oneof_schema_3_validator: Optional[WorkspaceSearchQueryFilterNameContain] = None
    # data type: WorkspaceSearchQueryFilterNameEqual
    oneof_schema_4_validator: Optional[WorkspaceSearchQueryFilterNameEqual] = None
    # data type: WorkspaceSearchQueryFilterNamespaceContainAny
    oneof_schema_5_validator: Optional[WorkspaceSearchQueryFilterNamespaceContainAny] = None
    # data type: WorkspaceSearchQueryFilterNot
    oneof_schema_6_validator: Optional[WorkspaceSearchQueryFilterNot] = None
    # data type: WorkspaceSearchQueryFilterOr
    oneof_schema_7_validator: Optional[WorkspaceSearchQueryFilterOr] = None
    actual_instance: Optional[Union[WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr]] = None
    one_of_schemas: Set[str] = { "WorkspaceSearchQueryFilterAnd", "WorkspaceSearchQueryFilterMembersContainAny", "WorkspaceSearchQueryFilterNameContain", "WorkspaceSearchQueryFilterNameEqual", "WorkspaceSearchQueryFilterNamespaceContainAny", "WorkspaceSearchQueryFilterNot", "WorkspaceSearchQueryFilterOr" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WorkspaceSearchQueryFilter.model_construct()
        error_messages = []
        match = 0
        # validate data type: WorkspaceSearchQueryFilterAnd
        if not isinstance(v, WorkspaceSearchQueryFilterAnd):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterAnd`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterMembersContainAny
        if not isinstance(v, WorkspaceSearchQueryFilterMembersContainAny):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterMembersContainAny`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterNameContain
        if not isinstance(v, WorkspaceSearchQueryFilterNameContain):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterNameContain`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterNameEqual
        if not isinstance(v, WorkspaceSearchQueryFilterNameEqual):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterNameEqual`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterNamespaceContainAny
        if not isinstance(v, WorkspaceSearchQueryFilterNamespaceContainAny):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterNamespaceContainAny`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterNot
        if not isinstance(v, WorkspaceSearchQueryFilterNot):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterNot`")
        else:
            match += 1
        # validate data type: WorkspaceSearchQueryFilterOr
        if not isinstance(v, WorkspaceSearchQueryFilterOr):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceSearchQueryFilterOr`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WorkspaceSearchQueryFilter with oneOf schemas: WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WorkspaceSearchQueryFilter with oneOf schemas: WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into WorkspaceSearchQueryFilterAnd
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterAnd.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterMembersContainAny
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterMembersContainAny.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterNameContain
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterNameContain.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterNameEqual
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterNameEqual.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterNamespaceContainAny
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterNamespaceContainAny.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterNot
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterNot.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceSearchQueryFilterOr
        try:
            instance.actual_instance = WorkspaceSearchQueryFilterOr.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WorkspaceSearchQueryFilter with oneOf schemas: WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WorkspaceSearchQueryFilter with oneOf schemas: WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], WorkspaceSearchQueryFilterAnd, WorkspaceSearchQueryFilterMembersContainAny, WorkspaceSearchQueryFilterNameContain, WorkspaceSearchQueryFilterNameEqual, WorkspaceSearchQueryFilterNamespaceContainAny, WorkspaceSearchQueryFilterNot, WorkspaceSearchQueryFilterOr]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from openapi_client.models.workspace_search_query_filter_and import WorkspaceSearchQueryFilterAnd
from openapi_client.models.workspace_search_query_filter_not import WorkspaceSearchQueryFilterNot
from openapi_client.models.workspace_search_query_filter_or import WorkspaceSearchQueryFilterOr
# TODO: Rewrite to not use raise_errors
WorkspaceSearchQueryFilter.model_rebuild(raise_errors=False)

