# coding: utf-8

"""
    airfocus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-beta.33.61.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.workspace_bulk_create import WorkspaceBulkCreate
from openapi_client.models.workspace_bulk_delete import WorkspaceBulkDelete
from openapi_client.models.workspace_bulk_patch import WorkspaceBulkPatch
from openapi_client.models.workspace_bulk_update import WorkspaceBulkUpdate
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WORKSPACEBULKACTION_ONE_OF_SCHEMAS = ["WorkspaceBulkCreate", "WorkspaceBulkDelete", "WorkspaceBulkPatch", "WorkspaceBulkUpdate"]

class WorkspaceBulkAction(BaseModel):
    """
    WorkspaceBulkAction
    """
    # data type: WorkspaceBulkCreate
    oneof_schema_1_validator: Optional[WorkspaceBulkCreate] = None
    # data type: WorkspaceBulkDelete
    oneof_schema_2_validator: Optional[WorkspaceBulkDelete] = None
    # data type: WorkspaceBulkPatch
    oneof_schema_3_validator: Optional[WorkspaceBulkPatch] = None
    # data type: WorkspaceBulkUpdate
    oneof_schema_4_validator: Optional[WorkspaceBulkUpdate] = None
    actual_instance: Optional[Union[WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate]] = None
    one_of_schemas: Set[str] = { "WorkspaceBulkCreate", "WorkspaceBulkDelete", "WorkspaceBulkPatch", "WorkspaceBulkUpdate" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WorkspaceBulkAction.model_construct()
        error_messages = []
        match = 0
        # validate data type: WorkspaceBulkCreate
        if not isinstance(v, WorkspaceBulkCreate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceBulkCreate`")
        else:
            match += 1
        # validate data type: WorkspaceBulkDelete
        if not isinstance(v, WorkspaceBulkDelete):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceBulkDelete`")
        else:
            match += 1
        # validate data type: WorkspaceBulkPatch
        if not isinstance(v, WorkspaceBulkPatch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceBulkPatch`")
        else:
            match += 1
        # validate data type: WorkspaceBulkUpdate
        if not isinstance(v, WorkspaceBulkUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkspaceBulkUpdate`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WorkspaceBulkAction with oneOf schemas: WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WorkspaceBulkAction with oneOf schemas: WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into WorkspaceBulkCreate
        try:
            instance.actual_instance = WorkspaceBulkCreate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceBulkDelete
        try:
            instance.actual_instance = WorkspaceBulkDelete.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceBulkPatch
        try:
            instance.actual_instance = WorkspaceBulkPatch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkspaceBulkUpdate
        try:
            instance.actual_instance = WorkspaceBulkUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WorkspaceBulkAction with oneOf schemas: WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WorkspaceBulkAction with oneOf schemas: WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], WorkspaceBulkCreate, WorkspaceBulkDelete, WorkspaceBulkPatch, WorkspaceBulkUpdate]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


